/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentinfomationsystem;

import Database.DBAction;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import studentinfomationclass.Class_;
import studentinfomationclass.CreditStudent;
import studentinfomationclass.SignUp;
import Database.DBConnection;
import studentinfomationclass.Subject;

/**
 *
 * @author Bac
 */
public class Admin_addPoint extends javax.swing.JPanel {

    /**
     * Creates new form Admin_addPoint
     */
    public Admin_addPoint() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputDiemQT = new javax.swing.JTextField();
        btnDiemQT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputDiemCK = new javax.swing.JTextField();
        btnDiemCK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lableSinhVien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelLop = new javax.swing.JLabel();
        labelDiemTB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        inputMaLop = new javax.swing.JTextField();
        btnMaLop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();

        inputDiemQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDiemQTActionPerformed(evt);
            }
        });

        btnDiemQT.setText("Thêm");
        btnDiemQT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemQTActionPerformed(evt);
            }
        });

        jLabel1.setText("Điểm quá trình:");

        jLabel2.setText("Điểm cuối kì");

        inputDiemCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDiemCKActionPerformed(evt);
            }
        });

        btnDiemCK.setText("Thêm");
        btnDiemCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemCKActionPerformed(evt);
            }
        });

        jLabel3.setText("ĐiểmTB        :");

        jLabel4.setText("Sinh viên:");

        jLabel5.setText("Lớp         :");

        labelDiemTB.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDiemCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableSinhVien)
                            .addComponent(labelLop)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDiemTB)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDiemQT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiemQT)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableSinhVien))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDiemCK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiemCK)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLop))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiemTB))
                .addContainerGap())
        );

        jLabel6.setText("Mã lớp");

        inputMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaLopActionPerformed(evt);
            }
        });

        btnMaLop.setText("Tìm kiếm");
        btnMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaLopActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdate)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(inputMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnMaLop))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaLop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    protected ArrayList<SignUp> listSignUp = new ArrayList<SignUp>();
    private CreditStudent std;


    private void inputMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaLopActionPerformed
        // TODO add your handling code here:
        query_2();
    }//GEN-LAST:event_inputMaLopActionPerformed

    private void btnMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaLopActionPerformed
        // TODO add your handling code here:
        query_2();
    }//GEN-LAST:event_btnMaLopActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //  double diemTB = getDiemTB(ipDiemQT, ipDiemCK);
        //  int mssv = Integer.parseInt(lableSinhVien.getText());
        int idlop = Integer.parseInt(labelLop.getText());
        Connection conn = null;
        PreparedStatement ptmt = null;
        DBConnection db = new DBConnection();
        conn = db.ketNoi();
        String sql = "update dangki set diemqt = (?), diemck =(?), diemtb =(?) , loai =(?) where sinhvien_mssv =(?) and lop_idlop = " + idlop + "";
        try {
            double midpoint = 0;
            double endpoint = 0;
            double averpoint = 0;
            String type = null;
            ptmt = conn.prepareStatement(sql);
            for (int i = 0; i < listSignUp.size(); i++) {
                if (idlop == listSignUp.get(i).getCl().getIdClass()) {
                    midpoint = listSignUp.get(i).getMidPoint();
                    endpoint = listSignUp.get(i).getEndPoint();
                    type = listSignUp.get(i).getType();
                    ptmt.setDouble(1, midpoint);
                    ptmt.setDouble(2, endpoint);
                    averpoint = getDiemTB(listSignUp.get(i).getMidPoint(), listSignUp.get(i).getEndPoint());
                    ptmt.setDouble(3, averpoint);
                    ptmt.setString(4, type);
                    ptmt.setInt(5, i + 1);
                    ptmt.executeUpdate();
                }
            }
            JOptionPane.showMessageDialog(null, "Update thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDiemCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemCKActionPerformed
        // TODO add your handling code here:
        if (!inputMaLop.getText().equals("")) {
            ipDiemCK = Double.parseDouble(this.inputDiemCK.getText());
            if (0 <= ipDiemCK && ipDiemCK <= 10) {
                datamodel.setValueAt(ipDiemCK, row, 1);
                double diemTB = getDiemTB(ipDiemQT, ipDiemCK);
                xeploai(diemTB);
                datamodel.setValueAt(diemTB, row, 2);
                datamodel.setValueAt(loai, row, 5);
                listSignUp.get(row).setEndPoint(ipDiemCK);
                listSignUp.get(row).setAverPoint(diemTB);
                listSignUp.get(row).setType(loai);
                labelDiemTB.setText(String.valueOf(diemTB));
                jTable1.setModel(datamodel);
                this.inputDiemCK.setText("");
                JOptionPane.showMessageDialog(null, "Nhập thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Nhập không đúng", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã lớp", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDiemCKActionPerformed

    private void inputDiemCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDiemCKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDiemCKActionPerformed

    private void btnDiemQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemQTActionPerformed
        if (!inputMaLop.getText().equals("")) {
            ipDiemQT = Double.parseDouble(this.inputDiemQT.getText());
            if (0 <= ipDiemQT && ipDiemQT <= 10) {
                datamodel.setValueAt(ipDiemQT, row, 0);
                listSignUp.get(row).setMidPoint(ipDiemQT);
                jTable1.setModel(datamodel);
                this.inputDiemQT.setText("");
                JOptionPane.showMessageDialog(null, "Nhập thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Nhập không đúng", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã lớp", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDiemQTActionPerformed

    private void inputDiemQTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDiemQTActionPerformed

    }//GEN-LAST:event_inputDiemQTActionPerformed
    // TODO add title columns 
    public void query_1() {
        Object[] oj = loadColumnName();
        for (int i = 0; i < oj.length; i++) {
            datamodel.addColumn(oj[i]);
        }
        jTable1.setModel(datamodel);
    }

    // TODO retrieve number of Student from Class
    public void query_2() {

        datamodel.getDataVector().clear();
        listSignUp.clear();

        text = inputMaLop.getText();
        if (text.equals("")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập mã lớp", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ArrayList<CreditStudent> ar = new ArrayList();
            ar = DBAction.viewTable(text);
            ArrayList<Subject> subj;
            if (ar != null) {
                for (int i = 0; i < ar.size(); i++) {
                    subj = new ArrayList();
                    subj.add(DBAction.selectSubjectAdm(text, Integer.toString(ar.get(i).getIdStu())));
                    for (int j = 0; j < subj.size(); j++) {
                        datamodel.addRow(loadRowData(subj.get(j).getMidPoint(), subj.get(j).getEndPoint(),
                                 subj.get(j).getAverPoint(), ar.get(i).getIdStu(),
                                subj.get(j).getCl().getIdClass(), subj.get(j).getType()));
                    }
                }
                jTable1.setModel(datamodel);
                TableClick();

            } else {
                JOptionPane.showMessageDialog(null, "Lớp không tồn tại", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    public void TableClick() {
        ipDiemCK = 0;
        ipDiemQT = 0;
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                row = jTable1.rowAtPoint(e.getPoint());
                col = jTable1.columnAtPoint(e.getPoint());
                if (row > -1 && col > -1) {
                    inputDiemQT.setText(String.valueOf(listSignUp.get(row).getMidPoint()));
                    inputDiemCK.setText(String.valueOf(listSignUp.get(row).getEndPoint()));
                    labelDiemTB.setText(String.valueOf(listSignUp.get(row).getAverPoint()));
                    labelLop.setText(String.valueOf(listSignUp.get(row).getCl().getIdClass()));
                    lableSinhVien.setText(String.valueOf(listSignUp.get(row).getCreStd().getIdStu()));
                }

            }
        });
    }

    private void update() {

    }

    private double getDiemTB(double diemqt, double diemck) {
        double a = (diemqt * this.hesogiuaky + diemck * this.hesocuoiky) * 1000;
        double b = Math.round(a);
        return b / 1000;
    }

    private void xeploai(double diemTB) {
        if (diemTB < 4) {
            loai = "F";
        } else if (4 <= diemTB && diemTB < 5.5) {
            loai = "D";
        } else if (5.5 <= diemTB && diemTB < 7) {
            loai = "C";
        } else if (7 <= diemTB && diemTB < 8.5) {
            loai = "B";
        } else {
            loai = "A";
        }
    }

    private Object[] loadRowData(double pos_1, double pos_2, double pos_3, int pos_4, int pos_5, String pos_6) {
        return new Object[]{pos_1, pos_2, pos_3, pos_4, pos_5, pos_6};
    }

    private Object[] loadColumnName() {
        return new Object[]{"Điểm QT", "Điểm CK", "Điểm TB", "MSSV", "Id lớp", "Loại"};
    }
    private int col;
    private int row;
    private String loai = null;
    private double ipDiemQT = 0;
    private double ipDiemCK = 0;
    private String text = null;
    private final double hesogiuaky = 0.3;
    private final double hesocuoiky = 0.7;
    private DefaultTableModel datamodel = new DefaultTableModel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiemCK;
    private javax.swing.JButton btnDiemQT;
    private javax.swing.JButton btnMaLop;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField inputDiemCK;
    private javax.swing.JTextField inputDiemQT;
    private javax.swing.JTextField inputMaLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDiemTB;
    private javax.swing.JLabel labelLop;
    private javax.swing.JLabel lableSinhVien;
    // End of variables declaration//GEN-END:variables
}
